<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px" size="medium"
    @submit.native.prevent>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell" style="width: 80px !important">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </el-form>
  
</template>

<script>
  export default {
    components: {},
    props: {},
    data() {
      return {
        formData: {},
        rules: {},
      }
    },
    computed: {},
    watch: {},
    created() {},
    mounted() {},
    methods: {
      submitForm() {
        this.$refs['vForm'].validate(valid => {
          if (!valid) return
          //TODO: 提交表单
        })
      },
      resetForm() {
        this.$refs['vForm'].resetFields()
      }
    }
  }
  
</script>

<style lang="less">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }
  
  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }
    
    .el-rate {
      margin-top: 8px;
    }
  }
  
  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }
    
    .el-rate {
      margin-top: 6px;
    }
  }
  
  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }
    
    .el-rate {
      margin-top: 4px;
    }
  }
  
  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }
  
  .clear-fix:after {
    clear: both;
  }
  
  .float-right {
    float: right;
  }
  
</style>

<style lang="less" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }
  
  div.tab-container {}
  
  .label-left-align ::v-deep .el-form-item__label {
    text-align: left;
  }
  
  .label-center-align ::v-deep .el-form-item__label {
    text-align: center;
  }
  
  .label-right-align ::v-deep .el-form-item__label {
    text-align: right;
  }
  
  .custom-label {}
  
  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
      margin: 0;
    }
  }
  
</style>